import { type FormEvent, useCallback, useEffect, useState } from 'react'
import { operatorId, type ApiItem, get } from '../api/client'
import { putQueue, type QueuedWrite } from '../offline'
import { type AppText } from '../types'
import { Empty, ErrorMessage } from '../components'

export function Batches({ t }: { t: AppText }) {
  const [items, setItems] = useState<ApiItem[]>([]); const [selected, setSelected] = useState<ApiItem | null>(null); const [showForm, setShowForm] = useState(false); const [message, setMessage] = useState('')
  const load = useCallback(() => { void get('/batches').then((data) => setItems(data.items ?? [])).catch((e: Error) => setMessage(e.message)) }, [])
  useEffect(load, [load])
  useEffect(() => { const refresh = () => load(); const reject = (event: Event) => { const detail = (event as CustomEvent<QueuedWrite>).detail; if (detail.path === '/batches') { setItems((current) => current.filter((item) => !item.queued)); setMessage(detail.lastError ?? 'Queued batch rejected') } }; window.addEventListener('chronofish:queue-drained', refresh); window.addEventListener('chronofish:queue-rejected', reject); return () => { window.removeEventListener('chronofish:queue-drained', refresh); window.removeEventListener('chronofish:queue-rejected', reject) } }, [load])
  if (selected) return <BatchDetail batch={selected} onBack={() => setSelected(null)} />
  const addQueued = (batch: ApiItem) => { setItems((current) => [{ ...batch, id: `queued-${Date.now()}`, queued: true }, ...current]); setShowForm(false); setMessage('Saved offline; will sync when online') }
  return <section><div className="page-heading"><div><p className="eyebrow">EXPERIMENTS</p><h1>{t.batches}</h1><p className="muted">Create batches, pin timing, and add injection lots.</p></div><button className="button button--primary" onClick={() => setShowForm(!showForm)}>+ {t.save}</button></div>{message && <ErrorMessage message={message} />}{showForm && <BatchForm onSaved={() => { setShowForm(false); load() }} onQueued={addQueued} />}{items.length === 0 ? <Empty message={t.empty} /> : <div className="list">{items.map((item) => <button className="list-row" key={String(item.id)} onClick={() => setSelected(item)}><span><strong>{String(item.batchCode)}</strong><small>{String(item.experimentDate)} · {String(item.timingProfileId ?? '')}</small></span><span className="pill">{item.queued ? 'queued' : 'active'}</span></button>)}</div>}</section>
}

export function BatchDetail({ batch, onBack }: { batch: ApiItem; onBack: () => void }) {
  const [detail, setDetail] = useState<ApiItem | null>(null); const [embryos, setEmbryos] = useState<Record<string, ApiItem[]>>({}); const [donorCellLineId, setDonorCellLineId] = useState(''); const [lotNo, setLotNo] = useState('1'); const [count, setCount] = useState(1); const [message, setMessage] = useState('')
  const load = useCallback(() => { void get(`/batches/${batch.id}`).then(async (value) => { setDetail(value); const lots = (value.injectionLots as ApiItem[] | undefined) ?? []; const loaded = await Promise.all(lots.map(async (lot: ApiItem) => [String(lot.id), (await get(`/injection-lots/${lot.id}/embryos?aliveOnly=false`)).items ?? []] as [string, ApiItem[]])); setEmbryos(Object.fromEntries(loaded)) }).catch((e: Error) => setMessage(e.message)) }, [batch.id])
  useEffect(load, [load])
  const createLot = async (event: FormEvent) => { event.preventDefault(); try { const result = await putQueue(`/batches/${batch.id}/injection-lots`, { lotNo, donorCellLineId, activatedAt: new Date().toISOString(), nActivated: count }); if (result.queued) setMessage('Lot saved offline; it will sync automatically'); else { setMessage('Lot created'); load() } } catch (e) { setMessage((e as Error).message) } }
  const addEmbryos = async (lotId: string) => { try { const result = await putQueue(`/injection-lots/${lotId}/embryos`, { count }); if (result.queued) setMessage('Embryos queued for sync'); else { setMessage('Embryos added'); load() } } catch (e) { setMessage((e as Error).message) } }
  return <section><button className="back" onClick={onBack}>← Batches</button><div className="page-heading"><div><p className="eyebrow">EXPERIMENT</p><h1>{String(batch.batchCode)}</h1><p className="muted">{String(batch.experimentDate)} · {String(batch.siteId ?? '')}</p></div></div>{message && <ErrorMessage message={message} />}<form className="form-card form-card--inline" onSubmit={createLot}><label>Lot number<input required value={lotNo} onChange={(event) => setLotNo(event.target.value)} /></label><label>Donor cell line<input required value={donorCellLineId} onChange={(event) => setDonorCellLineId(event.target.value)} /></label><label>Embryos<input required type="number" min="1" max="96" value={count} onChange={(event) => setCount(Number(event.target.value))} /></label><button className="button button--primary" type="submit">Create lot</button></form>{(detail?.injectionLots ?? []).map((lot: ApiItem) => <article className="form-card" key={String(lot.id)}><div className="page-heading"><div><h2>Lot {String(lot.lotNo)}</h2><p className="muted">{String(lot.nActivated ?? 0)} activated · {String(lot.activatedAt ?? '')}</p></div><button className="button button--secondary" type="button" onClick={() => addEmbryos(String(lot.id))}>Add {count} embryos</button></div><div className="list">{(embryos[String(lot.id)] ?? []).map((embryo) => <div className="list-row" key={String(embryo.id)}><span><strong>{String(embryo.embryoCode)}</strong><small>Well {String(embryo.wellPosition ?? '')}</small></span><span className="pill">{embryo.exitAt ? 'exited' : 'alive'}</span></div>)}</div></article>)}</section>
}

export function BatchForm({ onSaved, onQueued }: { onSaved: () => void; onQueued: (batch: ApiItem) => void }) {
  const [form, setForm] = useState({ experimentDate: new Date().toISOString().slice(0, 10), siteId: '', operatorId: operatorId(), protocolId: '01900000-0000-7000-8000-000000000001', treatmentGroupId: '' }); const [sites, setSites] = useState<ApiItem[]>([]); const [error, setError] = useState('')
  useEffect(() => { void get('/sites').then((data) => setSites(data.items ?? [])) }, [])
  const submit = async (event: FormEvent) => { event.preventDefault(); try { const result = await putQueue('/batches', form) as ApiItem; result.queued ? onQueued(form) : onSaved() } catch (e) { setError((e as Error).message) } }
  return <form className="form-card" onSubmit={submit}><label>Experiment date<input type="date" required value={form.experimentDate} onChange={(e) => setForm({ ...form, experimentDate: e.target.value })} /></label><label>Site<select required value={form.siteId} onChange={(e) => setForm({ ...form, siteId: e.target.value })}><option value="">Select site</option>{sites.map((site) => <option key={String(site.id)} value={String(site.id)}>{String(site.code)} — {String(site.name)}</option>)}</select></label><label>Treatment group<input required value={form.treatmentGroupId} onChange={(e) => setForm({ ...form, treatmentGroupId: e.target.value })} /></label>{error && <ErrorMessage message={error} />}<button className="button button--primary" type="submit">Save batch</button></form>
}
