import { useCallback, useEffect, useState } from 'react'
import { type ApiItem, get } from '../api/client'
import { putQueue } from '../offline'
import { type AppText } from '../types'
import { Empty, ErrorMessage } from '../components'

export function Due({ t, onPendingChange }: { t: AppText; onPendingChange: (count: number) => void }) {
  const [data, setData] = useState<ApiItem>({ overdue: [], upcoming: [] }); const [selected, setSelected] = useState<ApiItem | null>(null); const [error, setError] = useState('')
  const load = useCallback(() => { void get('/due-checkpoints').then((value) => { setData(value); onPendingChange(value.pendingPromotionCount ?? 0) }).catch((e: Error) => setError(e.message)) }, [onPendingChange])
  useEffect(() => { load(); const timer = window.setInterval(load, 60_000); return () => window.clearInterval(timer) }, [load])
  if (selected) return <Checkpoint due={selected} t={t} onBack={() => setSelected(null)} />
  const items = [...(data.overdue ?? []), ...(data.upcoming ?? [])]
  return <section><div className="page-heading"><div><p className="eyebrow">STAGE 1</p><h1>{t.due}</h1><p className="muted">Sorted by urgency. Refreshes every 60 seconds.</p></div><button className="button button--secondary" onClick={load}>{t.refresh}</button></div>{error && <ErrorMessage message={error} />}{items.length === 0 ? <Empty message={t.empty} /> : <div className="list">{items.map((item: ApiItem) => { const late = item.minutesLate ?? 0; return <button key={`${item.injectionLotId}-${item.stageCode}`} className="list-row" onClick={() => setSelected(item)}><span><strong>{String(item.batchCode)} / Lot {String(item.lotNo)}</strong><small>{String(item.stageLabel)} · {String(item.stageCode)}</small></span><span className={late > 0 ? 'pill pill--late' : 'pill'}>{late > 0 ? `Late ${late} min` : 'Due soon'}</span></button> })}</div>}</section>
}

function Checkpoint({ due, t, onBack }: { due: ApiItem; t: AppText; onBack: () => void }) {
  const [entry, setEntry] = useState<ApiItem | null>(null); const [outcomes, setOutcomes] = useState<Record<string, string>>({}); const [conditions, setConditions] = useState<Record<string, string>>({}); const [notes, setNotes] = useState<Record<string, string>>({}); const [observedAt, setObservedAt] = useState(new Date().toISOString().slice(0, 16)); const [error, setError] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { void get(`/injection-lots/${due.injectionLotId}/checkpoints/${due.stageCode}`).then((value) => { setEntry(value); const nextOutcomes: Record<string, string> = {}; const nextConditions: Record<string, string> = {}; (value.embryos ?? []).forEach((embryo: ApiItem) => { nextOutcomes[String(embryo.embryoId)] = 'ALIVE'; nextConditions[String(embryo.embryoId)] = String(embryo.defaultCondition ?? 'NORMAL') }); setOutcomes(nextOutcomes); setConditions(nextConditions) }).catch((e: Error) => setError(e.message)) }, [due])
  const save = async () => { if (!entry) return; setSaving(true); const observations = (entry.embryos ?? []).map((embryo: ApiItem) => ({ clientUuid: crypto.randomUUID(), embryoId: embryo.embryoId, stageCode: due.stageCode, observedAt: new Date(observedAt).toISOString(), outcome: outcomes[String(embryo.embryoId)] ?? 'ALIVE', condition: conditions[String(embryo.embryoId)] ?? 'NORMAL', notes: notes[String(embryo.embryoId)] || null })); try { await putQueue('/observations/embryo', { observations }); onBack() } catch (e) { setError((e as Error).message) } finally { setSaving(false) } }
  const total = entry?.embryos?.length ?? 0; const observed = Object.keys(outcomes).length; const activatedAt = String(entry?.activatedAt ?? due.activatedAt ?? ''); const elapsedHours = activatedAt && !Number.isNaN(Date.parse(activatedAt)) ? Math.max(0, Math.floor((Date.parse(observedAt) - Date.parse(activatedAt)) / 3_600_000)) : null
  return <section><button className="back" onClick={onBack}>← {t.due}</button><div className="page-heading"><div><p className="eyebrow">{String(due.batchCode)} / LOT {String(due.lotNo)}</p><h1>{String(due.stageLabel)}</h1><p className="muted">{total} embryos · {String(due.stageCode)} · Progress {observed}/{total}{elapsedHours === null ? '' : ` · T+${elapsedHours}h`}</p></div><button className="button button--primary" disabled={saving || !entry} onClick={save}>{saving ? 'Saving…' : 'Save checkpoint'}</button></div>{error && <ErrorMessage message={error} />}<label className="form-card">Observed at<input type="datetime-local" value={observedAt} onChange={(event) => setObservedAt(event.target.value)} /></label>{entry && <div className="well-grid">{entry.embryos?.map((embryo: ApiItem) => { const id = String(embryo.embryoId); return <div className="well" key={id}><strong>{String(embryo.wellPosition ?? '—')}</strong><small>{String(embryo.embryoCode)}</small><label>Outcome<select value={outcomes[id] ?? 'ALIVE'} onChange={(event) => setOutcomes({ ...outcomes, [id]: event.target.value })}><option>ALIVE</option><option>DEAD</option><option>DEGENERATED</option><option>NOT_OBSERVED</option></select></label><label>Condition<select value={conditions[id] ?? 'NORMAL'} onChange={(event) => setConditions({ ...conditions, [id]: event.target.value })}><option>NORMAL</option><option>ABNORMAL</option><option>UNDETERMINED</option></select></label><label>Notes<input value={notes[id] ?? ''} onChange={(event) => setNotes({ ...notes, [id]: event.target.value })} /></label></div> })}</div>}</section>
}
