import { useEffect, useState } from 'react'
import { type ApiItem, get, request } from '../api/client'
import { type DashboardFilters, parseFilters, updateFilterURL, withFilters } from '../filters'
import { ErrorMessage, Metric, ReportPanel, ReportTable } from '../components'
import { FilterBar } from './dashboard'

interface PrintableReport { kpi: ApiItem | null; funnel: ApiItem[]; survival: ApiItem[]; deviation: ApiItem[]; abnormality: ApiItem[]; fishSurvival: ApiItem[]; gaps: ApiItem[]; loading: boolean; error: string }

export function Export() {
  const [filters, setFilters] = useState<DashboardFilters>(() => parseFilters()); const [message, setMessage] = useState('')
  useEffect(() => { const onPop = () => setFilters(parseFilters()); window.addEventListener('popstate', onPop); return () => window.removeEventListener('popstate', onPop) }, [])
  const download = async () => { try { const response = await request('/exports/excel', { method: 'POST', body: JSON.stringify({ locale: 'th', filters }) }); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'chronofish-export.xlsx'; link.click(); URL.revokeObjectURL(url) } catch (e) { setMessage((e as Error).message) } }
  return <><section className="export-controls"><div className="page-heading"><div><p className="eyebrow">SCR-17 / 14 SHEETS</p><h1>Export</h1><p className="muted">The workbook and printable report use the same URL filters.</p></div></div><FilterBar filters={filters} onChange={(next) => { setFilters(next); updateFilterURL(next) }} /><div className="action-grid"><button className="action-card" onClick={download}><span className="action-icon">↓</span><strong>Download Excel</strong><span>14 flat sheets with raw n and R analysis shape.</span></button><button className="action-card" onClick={() => window.print()}><span className="action-icon">▣</span><strong>Print / PDF</strong><span>Print the complete dashboard report.</span></button></div>{message && <ErrorMessage message={message} />}</section><PrintableDashboard filters={filters} /></>
}

export function PrintableDashboard({ filters }: { filters: DashboardFilters }) {
  const [report, setReport] = useState<PrintableReport>({ kpi: null, funnel: [], survival: [], deviation: [], abnormality: [], fishSurvival: [], gaps: [], loading: true, error: '' })
  useEffect(() => { let cancelled = false; setReport((current) => ({ ...current, loading: true, error: '' })); void Promise.all([get(withFilters('/analytics/kpi', filters)), get(withFilters('/analytics/funnel', filters)), get(withFilters('/analytics/survival', filters)), get(withFilters('/analytics/timing-deviation', filters)), get(withFilters('/analytics/abnormality-onset', filters)), get(withFilters('/analytics/fish-survival', filters)), get(withFilters('/analytics/observation-gaps', filters))]).then(([kpi, funnel, survival, deviation, abnormality, fishSurvival, gaps]) => { if (!cancelled) setReport({ kpi, funnel: funnel.items ?? [], survival: survival.items ?? [], deviation: deviation.items ?? [], abnormality: abnormality.items ?? [], fishSurvival: fishSurvival.items ?? [], gaps: gaps.items ?? [], loading: false, error: '' }) }).catch((error: Error) => { if (!cancelled) setReport((current) => ({ ...current, loading: false, error: error.message })) }); return () => { cancelled = true } }, [filters])
  const kpi = report.kpi
  return <section className="print-report" aria-labelledby="print-report-title"><div className="print-report__header"><p className="eyebrow">CHRONOFISH / DASHBOARD SUMMARY</p><h1 id="print-report-title">Experiment dashboard report</h1><p className="muted">Generated from the same filtered analytics endpoints as the dashboard.</p></div>{report.loading && <p className="notice">Loading dashboard panels...</p>}{report.error && <ErrorMessage message={report.error} />}{!report.loading && !report.error && <><div className="metric-grid"><Metric label="Activated embryos" value={kpi?.stage1?.nActivated ?? 0} /><Metric label="Promoted fish" value={kpi?.stage1?.nPromoted ?? 0} /><Metric label="Alive fish" value={kpi?.stage2?.nAlive ?? 0} /><Metric label="Batches" value={kpi?.stage1?.nBatches ?? 0} /></div><ReportPanel title="Development funnel"><div className="report-bars">{report.funnel.map((point) => <div className="report-bar" key={String(point.stageOrder)}><span>{String(point.stageLabel ?? point.stageCode ?? point.stageOrder ?? '—')}</span><div><i style={{ width: `${Math.min(100, Number(point.pctOfActivated ?? 0))}%` }} /></div><strong>{point.alive ?? 0}</strong></div>)}</div></ReportPanel><ReportPanel title="Discrete-time survival"><ReportTable headers={['Stage', 'Risk set', 'Alive', 'n prev', 'n dead', 'Survival']} rows={report.survival.map((point) => [String(point.stageLabel ?? point.stageOrder ?? '—'), point.riskSet ?? 0, point.alive ?? 0, point.nPrev ?? 0, point.nDead ?? 0, Number(point.surv ?? 0).toFixed(4)])} /></ReportPanel><ReportPanel title="Timing deviation"><ReportTable headers={['Stage', 'n', 'Mean H', 'Median H', 'SD H']} rows={report.deviation.map((point) => [String(point.stageLabel ?? point.stageOrder ?? '—'), point.n ?? 0, Number(point.meanDeviationH ?? 0).toFixed(3), Number(point.medianDeviationH ?? 0).toFixed(3), point.sdDeviationH == null ? '—' : Number(point.sdDeviationH).toFixed(3)])} /></ReportPanel><ReportPanel title="Abnormality onset / comparison groups"><ReportTable headers={['Stage', 'Count']} rows={report.abnormality.map((point) => [String(point.stageLabel ?? point.stageOrder ?? '—'), point.count ?? 0])} /></ReportPanel><ReportPanel title="Stage 2 fish survival"><ReportTable headers={['Date', 'Alive', 'Dead']} rows={report.fishSurvival.map((point) => [String(point.date ?? point.observedOn ?? '—'), point.alive ?? 0, point.dead ?? 0])} /></ReportPanel><ReportPanel title="Observation gaps"><ReportTable headers={['Fish', 'Last observed', 'Missed days']} rows={report.gaps.map((point) => [String(point.fishCode ?? '—'), String(point.lastObservedOn ?? '—'), point.missedDays ?? 0])} /></ReportPanel></>}</section>
}
