import { type FormEvent, useCallback, useEffect, useState } from 'react'
import { type ApiItem, get } from '../api/client'
import { putQueue, type QueuedWrite } from '../offline'
import { type AppText } from '../types'
import { Empty, ErrorMessage } from '../components'

type MasterResource = 'operators' | 'donor-cell-lines' | 'recipient-egg-lots' | 'csof-lots' | 'treatment-groups' | 'fish-boxes'
const masterConfig: Record<MasterResource, { label: string; fields: { key: string; label: string; type?: string; options?: string[] }[] }> = {
  operators: { label: 'Operators', fields: [{ key: 'name', label: 'Name' }] },
  'donor-cell-lines': { label: 'Donor cell lines', fields: [{ key: 'strain', label: 'Strain' }, { key: 'preparation', label: 'Preparation', options: ['DISSOCIATED', 'CHUNKS'] }, { key: 'batchCode', label: 'Batch code' }] },
  'recipient-egg-lots': { label: 'Recipient egg lots', fields: [{ key: 'breed', label: 'Breed' }, { key: 'lotDate', label: 'Lot date', type: 'date' }, { key: 'label', label: 'Label' }] },
  'csof-lots': { label: 'CSOF lots', fields: [{ key: 'lotCode', label: 'Lot code' }] },
  'treatment-groups': { label: 'Treatment groups', fields: [{ key: 'code', label: 'Code' }, { key: 'name', label: 'Name' }, { key: 'armType', label: 'Arm type', options: ['SCNT', 'NATURAL_BREEDING', 'IVF'] }] },
  'fish-boxes': { label: 'Fish boxes', fields: [{ key: 'boxCode', label: 'Box code' }, { key: 'siteId', label: 'Site ID' }] },
}

export function Master({ t }: { t: AppText }) {
  const [sites, setSites] = useState<ApiItem[]>([]); const [code, setCode] = useState(''); const [name, setName] = useState(''); const [editing, setEditing] = useState<ApiItem | null>(null); const [message, setMessage] = useState('')
  const load = useCallback(() => { void get('/sites').then((data) => setSites(data.items ?? [])).catch((e: Error) => setMessage(e.message)) }, [])
  useEffect(load, [load])
  useEffect(() => { const refresh = () => load(); const reject = (event: Event) => { const detail = (event as CustomEvent<QueuedWrite>).detail; if (detail.path === '/sites') { setSites((current) => current.filter((item) => !item.queued)); setMessage(detail.lastError ?? 'Queued site rejected') } }; window.addEventListener('chronofish:queue-drained', refresh); window.addEventListener('chronofish:queue-rejected', reject); return () => { window.removeEventListener('chronofish:queue-drained', refresh); window.removeEventListener('chronofish:queue-rejected', reject) } }, [load])
  const submit = async (event: FormEvent) => { event.preventDefault(); const draft = { code, name }; try { const result = await putQueue('/sites', draft); setCode(''); setName(''); if (result.queued) { setSites((current) => [{ ...draft, id: `queued-${Date.now()}`, queued: true }, ...current]); setMessage('Saved offline; will sync when online') } else { setMessage('Saved'); load() } } catch (e) { setMessage((e as Error).message) } }
  const editSite = async (event: FormEvent) => { event.preventDefault(); if (!editing) return; try { await putQueue(`/sites/${editing.id}`, { code: editing.code, name: editing.name, active: editing.active !== false }, 'application/json', 'PATCH'); setEditing(null); setMessage('Site updated'); load() } catch (e) { setMessage((e as Error).message) } }
  const inactivate = async (site: ApiItem) => { if (!window.confirm(`Inactivate ${String(site.code)}?`)) return; try { await putQueue(`/sites/${site.id}`, { active: false }, 'application/json', 'PATCH'); setMessage('Site inactivated'); load() } catch (e) { setMessage((e as Error).message) } }
  return <section><div className="page-heading"><div><p className="eyebrow">SCR-16</p><h1>{t.master}</h1><p className="muted">Edit and inactivate records without deleting history.</p></div></div><form className="form-card form-card--inline" onSubmit={submit}><label>Site code<input required value={code} onChange={(e) => setCode(e.target.value)} /></label><label>Site name<input required value={name} onChange={(e) => setName(e.target.value)} /></label><button className="button button--primary" type="submit">{t.save}</button></form>{editing && <form className="form-card form-card--inline" onSubmit={editSite}><label>Editing code<input required value={String(editing.code ?? '')} onChange={(e) => setEditing({ ...editing, code: e.target.value })} /></label><label>Editing name<input required value={String(editing.name ?? '')} onChange={(e) => setEditing({ ...editing, name: e.target.value })} /></label><button className="button button--primary">Save changes</button><button className="button button--secondary" type="button" onClick={() => setEditing(null)}>Cancel</button></form>}{message && <p className="notice" role="status">{message}</p>}{sites.length === 0 ? <Empty message={t.empty} /> : <div className="list">{sites.map((site) => <div className="list-row" key={String(site.id)}><span><strong>{String(site.code)}</strong><small>{String(site.name)}</small></span><span><span className="pill">{site.active === false ? 'inactive' : 'active'}</span><button className="inline-action" type="button" onClick={() => setEditing(site)}>Edit</button>{site.active !== false && <button className="inline-action inline-action--danger" type="button" onClick={() => void inactivate(site)}>Inactivate</button>}</span></div>)}</div>}<MasterCatalog /></section>
}

export function MasterCatalog() {
  const [resource, setResource] = useState<MasterResource>('operators'); const [items, setItems] = useState<ApiItem[]>([]); const [form, setForm] = useState<Record<string, string>>({}); const [editing, setEditing] = useState<ApiItem | null>(null); const [message, setMessage] = useState('')
  const config = masterConfig[resource]
  const load = useCallback(() => { void get(`/${resource}`).then((data) => setItems(data.items ?? [])).catch((e: Error) => setMessage(e.message)) }, [resource])
  useEffect(() => { setForm({}); setEditing(null); load() }, [load])
  useEffect(() => { const refresh = () => load(); const reject = (event: Event) => { const detail = (event as CustomEvent<QueuedWrite>).detail; if (detail.path === `/${resource}`) { setItems((current) => current.filter((item) => !item.queued)); setMessage(detail.lastError ?? 'Queued master record rejected') } }; window.addEventListener('chronofish:queue-drained', refresh); window.addEventListener('chronofish:queue-rejected', reject); return () => { window.removeEventListener('chronofish:queue-drained', refresh); window.removeEventListener('chronofish:queue-rejected', reject) } }, [load, resource])
  const submit = async (event: FormEvent) => { event.preventDefault(); try { const result = await putQueue(`/${resource}`, { ...form }); setForm({}); if (result.queued) { setItems((current) => [{ ...form, id: `queued-${Date.now()}`, queued: true }, ...current]); setMessage('Saved offline; will sync when online') } else { setMessage('Saved'); load() } } catch (e) { setMessage((e as Error).message) } }
  const saveEdit = async (event: FormEvent) => { event.preventDefault(); if (!editing) return; try { await putQueue(`/${resource}/${editing.id}`, editing, 'application/json', 'PATCH'); setEditing(null); setMessage('Record updated'); load() } catch (e) { setMessage((e as Error).message) } }
  const inactivate = async (item: ApiItem) => { if (!window.confirm('Inactivate this record?')) return; try { await putQueue(`/${resource}/${item.id}`, { active: false }, 'application/json', 'PATCH'); setMessage('Record inactivated'); load() } catch (e) { setMessage((e as Error).message) } }
  return <div className="master-catalog"><h2>All master data</h2><label>Resource<select value={resource} onChange={(event) => setResource(event.target.value as MasterResource)}>{Object.entries(masterConfig).map(([key, value]) => <option key={key} value={key}>{value.label}</option>)}</select></label><form className="form-card form-card--inline" onSubmit={submit}>{config.fields.map((field) => <label key={field.key}>{field.label}{field.options ? <select required value={form[field.key] ?? ''} onChange={(event) => setForm({ ...form, [field.key]: event.target.value })}><option value="">Select</option>{field.options.map((option) => <option key={option}>{option}</option>)}</select> : <input required={field.key !== 'batchCode' && field.key !== 'lotDate' && field.key !== 'siteId'} type={field.type ?? 'text'} value={form[field.key] ?? ''} onChange={(event) => setForm({ ...form, [field.key]: event.target.value })} />}</label>)}<button className="button button--primary" type="submit">Save</button></form>{editing && <form className="form-card form-card--inline" onSubmit={saveEdit}><label>Edit selected<input value={String(editing.name ?? editing.code ?? editing.label ?? editing.lotCode ?? editing.boxCode ?? editing.strain ?? '')} onChange={(event) => setEditing({ ...editing, name: event.target.value })} /></label><button className="button button--primary">Save changes</button><button className="button button--secondary" type="button" onClick={() => setEditing(null)}>Cancel</button></form>}{message && <p className="notice" role="status">{message}</p>}<div className="list">{items.map((item) => <div className="list-row" key={String(item.id)}><span><strong>{String(item.name ?? item.code ?? item.label ?? item.lotCode ?? item.boxCode ?? item.strain)}</strong></span><span><span className="pill">{item.active === false ? 'inactive' : 'active'}</span><button className="inline-action" type="button" onClick={() => setEditing(item)}>Edit</button>{item.active !== false && <button className="inline-action inline-action--danger" type="button" onClick={() => void inactivate(item)}>Inactivate</button>}</span></div>)}</div></div>
}
