import { type ChangeEvent, type FormEvent, useCallback, useEffect, useState } from 'react'
import { type ApiItem, get, request } from '../api/client'
import { putQueue, type QueuedWrite } from '../offline'
import { Empty, ErrorMessage } from '../components'

export function Timing() {
  const [profile, setProfile] = useState<ApiItem | null>(null); const [error, setError] = useState(''); const [importing, setImporting] = useState(false)
  const load = useCallback(() => { void get('/timing-profiles/current').then(setProfile).catch((e: Error) => setError(e.message)) }, [])
  useEffect(load, [load]); useEffect(() => { const refresh = () => load(); window.addEventListener('chronofish:queue-drained', refresh); return () => window.removeEventListener('chronofish:queue-drained', refresh) }, [load])
  const download = async () => { try { const response = await request('/timing-profiles/csv?protocolId=01900000-0000-7000-8000-000000000001'); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'timing-profile.csv'; link.click(); URL.revokeObjectURL(url) } catch (e) { setError((e as Error).message) } }
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setImporting(true); setError(''); try { const body = await file.text(); const result = await putQueue('/timing-profiles/csv', body, 'text/csv'); if (!result.queued) await load() } catch (e) { setError((e as Error).message) } finally { setImporting(false); event.target.value = '' } }
  return <section><div className="page-heading"><div><p className="eyebrow">SCR-15 / VERSIONED</p><h1>Timing profile</h1><p className="muted">Versioned expected HPA entries are pinned to each batch.</p></div><div className="button-row"><button className="button button--secondary" onClick={download}>Download CSV</button><label className="button button--secondary">{importing ? 'Importing…' : 'Import CSV'}<input className="sr-only" type="file" accept=".csv,text/csv" disabled={importing} onChange={upload} /></label></div></div>{error && <ErrorMessage message={error} />}{profile && <div className="table-wrap"><table><thead><tr><th>Stage</th><th>Label</th><th>Expected HPA</th></tr></thead><tbody>{(profile.entries as ApiItem[] | undefined ?? []).map((entry) => <tr key={String(entry.id ?? entry.stageCode)}><td>{String(entry.stageCode ?? entry.code)}</td><td>{String(entry.stageLabel ?? entry.label)}</td><td>{Number(entry.expectedHpa).toFixed(4)}</td></tr>)}</tbody></table></div>}</section>
}

export function Promotions() {
  const [items, setItems] = useState<ApiItem[]>([]); const [message, setMessage] = useState(''); const [queued, setQueued] = useState<string[]>([])
  const load = useCallback(() => { void get('/promotions/pending').then((data) => setItems(data.items ?? [])).catch((e: Error) => setMessage(e.message)) }, [])
  useEffect(load, [load]); useEffect(() => { const refresh = () => load(); const reject = (event: Event) => { const detail = (event as CustomEvent<QueuedWrite>).detail; if (detail.path === '/promotions') { setQueued([]); setMessage(detail.lastError ?? 'Promotion was rejected; review the candidate again') } }; window.addEventListener('chronofish:queue-drained', refresh); window.addEventListener('chronofish:queue-rejected', reject); return () => { window.removeEventListener('chronofish:queue-drained', refresh); window.removeEventListener('chronofish:queue-rejected', reject) } }, [load])
  const promote = async (item: ApiItem) => { const id = String(item.embryoId); setQueued((current) => [...current, id]); try { const result = await putQueue('/promotions', { promotions: [{ clientUuid: crypto.randomUUID(), embryoId: item.embryoId, fishCode: item.suggestedFishCode }] }); if (!result.queued) setItems((current) => current.filter((entry) => String(entry.embryoId) !== id)) } catch (e) { setQueued((current) => current.filter((entry) => entry !== id)); setMessage((e as Error).message) } }
  return <section><div className="page-heading"><div><p className="eyebrow">SCR-07 / CONFIRMATION REQUIRED</p><h1>Promotion</h1><p className="muted">Only the latest ALIVE observation at the configured elapsed-age threshold is eligible.</p></div><button className="button button--secondary" onClick={load}>Refresh</button></div>{message && <ErrorMessage message={message} />}{items.length === 0 ? <Empty message="No eligible embryo promotions" /> : <div className="list">{items.map((item) => { const id = String(item.embryoId); const isQueued = queued.includes(id); return <div className="list-row" key={id}><span><strong>{String(item.embryoCode)}</strong><small>DOB {String(item.dob)} · {String(item.condition ?? 'NORMAL')}</small></span><button className="button button--primary" disabled={isQueued} onClick={() => void promote(item)}>{isQueued ? 'Queued' : 'Confirm'}</button></div> })}</div>}</section>
}

export function Controls() {
  const [batchId, setBatchId] = useState(''); const [items, setItems] = useState<ApiItem[]>([]); const [message, setMessage] = useState('')
  const save = async (event: FormEvent) => { event.preventDefault(); try { await putQueue(`/batches/${batchId}/control-arm-counts`, { items }); setMessage('Control counts saved') } catch (e) { setMessage((e as Error).message) } }
  return <section><div className="page-heading"><div><p className="eyebrow">SCR-11 / CONTROL ARMS</p><h1>Control counts</h1><p className="muted">Record normal and abnormal counts for natural breeding or IVF arms.</p></div></div><form className="form-card" onSubmit={save}><label>Batch ID<input required value={batchId} onChange={(event) => setBatchId(event.target.value)} /></label><label>Stage code<input required value={items[0]?.stageCode ?? ''} onChange={(event) => setItems([{ armType: 'NATURAL_BREEDING', stageCode: event.target.value, nNormal: 0, nAbnormal: 0 }])} /></label><label>Normal<input type="number" min="0" value={items[0]?.nNormal ?? 0} onChange={(event) => setItems([{ ...(items[0] ?? {}), armType: 'NATURAL_BREEDING', nNormal: Number(event.target.value), nAbnormal: items[0]?.nAbnormal ?? 0 }])} /></label><label>Abnormal<input type="number" min="0" value={items[0]?.nAbnormal ?? 0} onChange={(event) => setItems([{ ...(items[0] ?? {}), armType: 'NATURAL_BREEDING', nNormal: items[0]?.nNormal ?? 0, nAbnormal: Number(event.target.value) }])} /></label><button className="button button--primary" type="submit">Save counts</button></form>{message && <p className="notice" role="status">{message}</p>}</section>
}
